title: Stackbit Fresh Theme
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    bg: dark
    has_nav: true
    has_social: true
    profile_img: images/avatar.png
    tagline: B.S. Computer Science\nB.A. Classical Culture
    title: Calvin Birchall-Roman
  layout_style: overflow
  palette: blue
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
