title: Calvin Birchall-Roman
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    bg: light
    has_nav: true
    has_social: true
    profile_img: images/avatar.png
    tagline: Computer Science / Classical Culture
    title: Calvin Birchall-Roman
  layout_style: default
  palette: violet
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
